language: go
sudo: false
go:
- 1.4
before_script:
- wget  https://dl.bintray.com/mitchellh/consul/0.5.0_linux_amd64.zip
- unzip 0.5.0_linux_amd64.zip
- mkdir consul_data
- mkdir demoCA && touch demoCA/index.txt && echo "0a" > demoCA/serial
- openssl req -subj "/C=US/ST=Awesome/L=Awesome/O=Awesome/CN=*.consul" -keyout ca.key.pem -new -x509 -days 30 -nodes -out ca.cert.pem
- openssl req -subj "/C=US/ST=Awesome/L=Awesome/O=Awesome/CN=*.consul" -keyout server.key.pem -new -nodes -out server.csr.pem
- openssl ca -batch -outdir . -days 60 -keyfile ca.key.pem -cert ca.cert.pem -notext -in server.csr.pem -out server.cert.pem
- openssl req -subj "/C=US/ST=Awesome/L=Awesome/O=Awesome/CN=*.consul" -keyout client.key.pem -new -nodes -out client.csr.pem
- openssl ca -batch -outdir . -days 60 -keyfile ca.key.pem -cert ca.cert.pem -notext -in client.csr.pem -out client.cert.pem
- echo '{"ca_file": "ca.cert.pem","cert_file": "server.cert.pem","key_file": "server.key.pem","verify_incoming": true,"verify_outgoing": true,"ports": {"https": 8501}}' > tls.json
- ./consul agent -server -bootstrap -data-dir=consul_data -config-file=tls.json &
- sleep 5
- git config --global user.email "ryan@ryanbreen.com"
- git config --global user.name "Ryan Breen"
script:
- go test
after_success:
- test ! $TRAVIS_TAG && exit
- go get -x github.com/mitchellh/gox
- gox -build-toolchain -osarch="linux/amd64 darwin/amd64 windows/amd64"
- gox -output="build/{{.OS}}/{{.Arch}}/{{.Dir}}" -osarch="linux/amd64 darwin/amd64 windows/amd64"
- curl -T build/darwin/amd64/fsconsul -uryanbreen:$BINTRAY_KEY https://api.bintray.com/content/cimpress-mcp/Go/fsconsul/$TRAVIS_TAG/$TRAVIS_TAG/darwin-amd64/fsconsul
- curl -T build/linux/amd64/fsconsul -uryanbreen:$BINTRAY_KEY https://api.bintray.com/content/cimpress-mcp/Go/fsconsul/$TRAVIS_TAG/$TRAVIS_TAG/linux-amd64/fsconsul
- curl -T build/windows/amd64/fsconsul.exe -uryanbreen:$BINTRAY_KEY https://api.bintray.com/content/cimpress-mcp/Go/fsconsul/$TRAVIS_TAG/$TRAVIS_TAG/windows-amd64/fsconsul.exe
- curl -XPOST -uryanbreen:$BINTRAY_KEY https://api.bintray.com/content/cimpress-mcp/Go/fsconsul/$TRAVIS_TAG/publish
env:
  global:
  - secure: E3uZL0mrudFxOowDIt+ruTlg5HVZJyGRXoZ/XwLG0ukW+T+Zhh81B7PTiWM2DO34OIcHRYozqutn+P9gf/avJ+2K7I0gWc/8peLff7tn+bWGtY9UNMCF328KTlKEDUW86QcxM50cGblLCKq1R+K7UnpJP8cePvTqD0z/3zA4wyo=
