language: go

go:
    - 1.3

before_script:
  - wget  https://dl.bintray.com/mitchellh/consul/0.4.0_linux_amd64.zip
  - unzip 0.4.0_linux_amd64.zip
  - mkdir consul_data
  - ./consul agent -server -bootstrap -data-dir=consul_data &
  - sleep 2
  - git config --global user.email "ryan@ryanbreen.com"
  - git config --global user.name "Ryan Breen"

script:
  - go test
  - go install